# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy github pages CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm i
          npm run docs:build
          echo 'blog.x-ray.work' > docs/.vuepress/dist/CNAME
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PRIVATE_TOKEN }}
        with:
          source-directory: 'docs/.vuepress/dist'
          destination-github-username: 'x-ray-s'
          destination-repository-name: 'x-ray-s.github.io'
          user-email: princesswar721@gmail.com
          target-branch: master
